default_language_version:
    python: python3

exclude: vendor

repos:
    - repo: https://github.com/astral-sh/ruff-pre-commit
      rev: v0.4.8
      hooks:
        - id: ruff
          args: [ --fix, --show-fixes, --exit-non-zero-on-fix ]
        - id: ruff-format
    - repo: https://github.com/pycqa/isort
      rev: 5.12.0
      hooks:
        - id: isort
